### ISSUE TITLE
faild

### ISSUE THREAD

**Issue by noaims** [amirsadeghi1/hamster_kombat_agent#2]
Getting info user...Traceback (most recent call last):
  File "/opt/hamster_kombat_agent/hamster.py", line 490, in <module>
    main()
  File "/opt/hamster_kombat_agent/hamster.py", line 398, in main
    process_clicker_data(clicker_data, token, claimed_ciphers, cipher_text, auto_upgrade_energy, auto_upgrade_multitap, cek_task_list, cek_task_dict, auto_upgrade_passive)
NameError: name 'cipher_text' is not defined

**Comment by amirsadeghi1** [comment]
When you run the bot, it will ask you for inputs that if you activate the ciphertext check, you must enter its word in the next message.
The error you sent means that you did not insert the ciphertext!
